build:
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-cid-token -p $CI_JOB_TOKEN "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"