build image:
  image: docker
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -U $CI_REGISTRY_USERNAME $CI_REGISTRY --password-stdin
    - docker build -t $CU_REGISTRY_IMAGE .
    - docker push $CU_REGISTRY_IMAGE