stages:
  - build
  - test
  - deploy
  - testserver
  - production

build-job:       # This job runs in the build stage, which runs first.
  image: npm:latest
  stage: build
  artifacts:
    name: "artifacts"
    paths:
      - .next/
  script:
    #- yarn install
    #- yarn run build
    #- echo "Compile complete."
    - echo "Success build"

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
testserver-job:
  image: alpine:latest
  stage: testserver
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $MS7_HOST_ADDR >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "Success run before_script"
  script:
    - echo "Start clone with gitlab repository "
    - ssh root@$MS7_HOST_ADDR -p 22109 "hostname && echo 'Welcome!!!' > welcome.txt"
    #- git clone http://gitlab-ci-token:${ms7_gitlab_token}@lab.rixoshop.com/atramart/ms7.git
    - git remote set-url origin ssh://ms@"${MS7_HOST_ADDR}":22109/opt/git/ms5
    - git checkout -b master
    - git push origin master
    - echo "push success"
  allow_failure: false
  when : on_success 
  environment:
    name: root
    url: "${MS7_HOST_ADDR}"
  only:
    - main
production-job:
  image: alpine:latest
  stage: production
  # before_script:
  #   - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
  #   - eval $(ssh-agent -s)
  #   - echo "${SSH_PRIVATE_KEY}" | ssh-add -
  #   - mkdir -p ~/.ssh
  #   - chmod 700 ~/.ssh
  #   - ssh-keyscan $MS7_HOST_ADDR >> ~/.ssh/known_hosts
  #   - chmod 644 ~/.ssh/known_hosts
  #   - echo "Success run before_script"
  script:
    - echo "Start clone with gitlab repository"
  #   - ssh root@$MS7_HOST_ADDR "hostname && echo 'Welcome!!!' > welcome.txt"
  #   #- git clone http://gitlab-ci-token:${ms7_gitlab_token}@lab.rixoshop.com/atramart/ms7.git
  #   - git remote set-url origin ssh://root@"${MS7_HOST_ADDR}":22/opt/git/ms/ms7
  #   - git push origin master
  #   - echo "push success"
  # allow_failure: false
  # when : on_success
  # environment:
  #   name: root
  #   url: "${MS7_HOST_ADDR}"
  # only:
  #   - main
