import localFont from "next/font/local";
import "./styles/globals.css";
import "./styles/icon.css";

export const metadata = {
  title: "فروشگاه اینترنتی آترامارت",
  description: "Generated by Next.js",
};
const iranSansXV = localFont({
  src: "../public/fonts/iransansxv.woff",
  variable: "--iransansXV",
});
const atraIcon = localFont({
  src: "../public/fonts/icomoon.woff",
  variable: "--font-icon",
  display: "block",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={`${iranSansXV.variable} ${atraIcon.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
