import localFont from 'next/font/local';
import './styles/globals.css';

export const metadata = {
  title: 'آترامارت',
  description: 'Generated by Next.js',
};
const iranSansXV = localFont({
  src: '../public/fonts/iransansxv.woff',
  variable: '--iransansXV',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fa-IR"
      dir="rtl"
      className={`${iranSansXV.variable} antialiased`}
    >
      <body>{children}</body>
    </html>
  );
}
